---
name: Release
on:
  release:
    types:
      - released
#      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Set version
        run: |
          echo "RELEASE_VERSION=$(${{ github.event.release.tag_name }} | sed -e s/^v//)" >> $GITHUB_ENV
      - name: Print version
        run: |
          echo "going to release with version ${{ env.RELEASE_VERSION }}"
#      - name: build publish
#        run: ./gradlew clean build publish --no-daemon --info --stacktrace -Pversion="${{ env.RELEASE_VERSION }}"
#        timeout-minutes: 10
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
#          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}
#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
...
